version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: SongsApp
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./back   # Path to your NestJS project
      dockerfile: Dockerfile
    container_name: nest_backend
    restart: always
    environment:
      NODE_ENV: production
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 1234
      DATABASE_NAME: SongsApp
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./front  # Path to your Vite React project
      dockerfile: Dockerfile
    container_name: react_frontend
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  db_data:
